const roles=["vision","images","attributes"];
const $=id=>document.getElementById(id);
async function api(url,options={}){const r=await fetch(url,options);const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.error||`HTTP ${r.status}`);return d}
function notice(text,error=false){$("notice").textContent=text;$("notice").className=`notice ${error?"error":"ok"}`}
function renderRole(role,value){const card=document.createElement("article");card.className="model-card";card.dataset.role=role;card.innerHTML=`<h2></h2><p class="key-state"></p><label>API 地址<input class="base-url" type="url"></label><label>API Key<input class="api-key" type="password" autocomplete="new-password"></label><label>模型名称<input class="model"></label><button class="test">测试模型连通</button><small class="test-result">尚未测试</small>`;card.querySelector("h2").textContent=value.label;card.querySelector(".key-state").textContent=value.has_key?"密钥已加密保存，留空不会覆盖":"尚未保存密钥";card.querySelector(".base-url").value=value.base_url;card.querySelector(".api-key").placeholder=value.has_key?"已保存，留空不覆盖":"粘贴你自己账号的 API Key";card.querySelector(".model").value=value.model;card.querySelector(".test").onclick=async()=>{const out=card.querySelector(".test-result");out.textContent="连接中…";try{const d=await api(`/api/model-settings/${role}/test`,{method:"POST"});out.textContent=`连接成功（HTTP ${d.http_status}）`}catch(e){out.textContent=`连接失败：${e.message}`}};return card}
async function load(){try{const d=await api("/api/model-settings");const root=$("modelCards");root.innerHTML="";roles.forEach(role=>root.appendChild(renderRole(role,d.roles[role])));$("imageLanguage").value=d.strategy.image_language;$("referenceCount").value=d.strategy.reference_image_count;$("generatePerSku").checked=d.strategy.generate_per_sku;$("autoProcess").checked=d.strategy.auto_process_after_collection;notice(d.vault_error||"配置已读取。",!!d.vault_error)}catch(e){notice(e.message,true)}}
async function saveAll(){const payload={roles:{},strategy:{image_language:$("imageLanguage").value,reference_image_count:Number($("referenceCount").value),generate_per_sku:$("generatePerSku").checked,auto_process_after_collection:$("autoProcess").checked}};document.querySelectorAll(".model-card").forEach(card=>payload.roles[card.dataset.role]={base_url:card.querySelector(".base-url").value,model:card.querySelector(".model").value,api_key:card.querySelector(".api-key").value});$("saveHint").textContent="正在加密保存…";try{await api("/api/model-settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});notice("设置已保存，密钥已用 Windows DPAPI 加密。现在可以测试连接。");$("saveHint").textContent="已保存；可以点击模型卡片中的连接测试";await load();window.scrollTo({top:0,behavior:"smooth"})}catch(e){notice(e.message,true);$("saveHint").textContent=`保存失败：${e.message}`}}
$("saveAll").onclick=saveAll;$("saveDock").onclick=saveAll;
load();
