let allItems=[],processingItems=[],filteredItems=[],page=1;
const pageSize=20,selected=new Set(),processingStages=new Set(["BLOCKED_EVIDENCE","CAPTURE_READY","READY_FOR_AI","AI_PROCESSING","AI_PAUSED","AI_FAILED","READ_ERROR"]),$=id=>document.getElementById(id);
const stageLabel=stage=>({BLOCKED_EVIDENCE:"缺资料",CAPTURE_READY:"采集资料待确认",READY_FOR_AI:"可生成 AI",AI_PROCESSING:"AI 处理中",AI_PAUSED:"AI 已暂停",AI_FAILED:"AI 失败",READY_FOR_HUMAN_REVIEW:"待审核",READY_TO_PUBLISH:"待发布",PUBLISHED:"发布成功",PUBLISH_PARTIAL:"部分成功",READ_ERROR:"读取失败"}[stage]||stage||"未知");
const imageUrl=item=>item.thumbnail?.startsWith("assets/")?`/assets/${item.thumbnail.slice(7)}`:`/api/image-proxy?url=${encodeURIComponent(item.thumbnail||"")}`;
async function api(url,options={}){const response=await fetch(url,options),data=await response.json();if(!response.ok||data.ok===false)throw new Error(data.error||`HTTP ${response.status}`);return data}
function readableAiError(error){const text=String(error||"").trim();if(/read operation timed out|timed out/i.test(text))return "AI 服务等待超时：本次未生成任何内容，可点击“重新运行 AI 流程”重试（最长等待 300 秒）。";return text||"查看 AI 日志后重试"}
function statusText(item){if(item.full_ai_status==="failed")return `完整 AI 流程失败：${readableAiError(item.full_ai_error)}`;if(["queued","running"].includes(item.full_ai_status))return `${item.full_ai_stage||"AI 处理中"} ${item.full_ai_progress||0}%｜${item.full_ai_message||""}`;if(item.full_ai_status==="paused")return "完整 AI 流程已暂停，可重新运行";return item.errors?.length?`补齐证据：${item.errors.join("；")}`:(item.next_action||"")}
function currentPage(){return filteredItems.slice((page-1)*pageSize,page*pageSize)}
function updateSelection(){const count=selected.size;$("selectedCount").textContent=`已选 ${count} 条`;["enterReviewSelected","pauseSelected","copySelected","recycleSelected"].forEach(id=>$(id).disabled=!count);const names=currentPage().map(x=>x.name);$("selectAll").checked=!!names.length&&names.every(name=>selected.has(name))}
function render(){
  const counts={BLOCKED_EVIDENCE:0,READY_FOR_AI:0,READY_FOR_HUMAN_REVIEW:0,READY_TO_PUBLISH:0,PUBLISHED:0,PUBLISH_PARTIAL:0,READ_ERROR:0};allItems.forEach(item=>counts[item.stage]=(counts[item.stage]||0)+1);
  const values=[["待处理",processingItems.length],["可生成 AI",counts.READY_FOR_AI],["待审核",counts.READY_FOR_HUMAN_REVIEW],["待发布",counts.READY_TO_PUBLISH],["发布成功",counts.PUBLISHED],["部分成功",counts.PUBLISH_PARTIAL],["缺资料",(counts.BLOCKED_EVIDENCE||0)+(counts.CAPTURE_READY||0)],["读取失败",counts.READ_ERROR]];
  $("stats").innerHTML=values.map(([label,value])=>`<div class="stat"><span>${label}</span><strong>${value||0}</strong></div>`).join("");$("stepProcessing").textContent=processingItems.length;$("stepReview").textContent=counts.READY_FOR_HUMAN_REVIEW||0;$("stepPublish").textContent=(counts.READY_TO_PUBLISH||0)+(counts.PUBLISHED||0)+(counts.PUBLISH_PARTIAL||0);$("resultCount").textContent=`${filteredItems.length} 条结果`;
  const totalPages=Math.max(1,Math.ceil(filteredItems.length/pageSize));if(page>totalPages)page=totalPages;$("pageInfo").textContent=`第 ${page} / ${totalPages} 页，共 ${filteredItems.length} 条`;$("prevPage").disabled=page<=1;$("nextPage").disabled=page>=totalPages;
  const root=$("rows");root.innerHTML="";currentPage().forEach(item=>{const row=document.createElement("div");row.className="row";row.innerHTML=`<label class="select-cell"><input type="checkbox"></label><div class="product-with-thumb"><img class="thumb" alt="商品首图"><div class="product"><strong></strong><small></small></div></div><span>1688</span><span class="image-count"></span><div><span class="badge"></span><small class="next"></small></div><div class="actions"><a class="view">查看</a><a class="edit">编辑</a><button class="log">AI 日志</button><button class="flow">完整 AI 流程</button></div>`;
    const checkbox=row.querySelector("input");checkbox.checked=selected.has(item.name);checkbox.onchange=()=>{checkbox.checked?selected.add(item.name):selected.delete(item.name);updateSelection()};const img=row.querySelector("img");img.src=imageUrl(item);img.onerror=()=>img.style.visibility="hidden";row.querySelector(".product strong").textContent=item.title;row.querySelector(".product small").textContent=item.source_url||item.name;row.querySelector(".image-count").textContent=`${item.image_count||0} 张`;row.querySelector(".badge").textContent=stageLabel(item.stage);row.querySelector(".next").textContent=statusText(item);row.querySelector(".view").href=`/editor?draft=${encodeURIComponent(item.name)}`;row.querySelector(".edit").href=`/editor?draft=${encodeURIComponent(item.name)}`;const flow=row.querySelector(".flow");flow.textContent=["queued","running"].includes(item.full_ai_status)?`${item.full_ai_progress||0}% 处理中`:(item.full_ai_status==="failed"||item.full_ai_status==="paused"?"重新运行 AI 流程":"完整 AI 流程");flow.disabled=["queued","running"].includes(item.full_ai_status)||["BLOCKED_EVIDENCE","READ_ERROR"].includes(item.stage);flow.onclick=()=>startFullFlow(item);row.querySelector(".log").onclick=()=>showLog(item);root.appendChild(row)});$("empty").style.display=filteredItems.length?"none":"block";updateSelection()
}
async function load(){try{const data=await api("/api/drafts");allItems=data.items||[];processingItems=allItems.filter(item=>processingStages.has(item.stage));filteredItems=[...processingItems];render();if(allItems.some(item=>["queued","running"].includes(item.full_ai_status)))setTimeout(load,2000)}catch(e){$("empty").textContent=`本机商品数据读取失败：${e.message}`}}
async function startFullFlow(item){const images=item.estimated_image_count||3;const skuNote=item.sku_count>1?`，其中 ${item.sku_count} 张为各 SKU 专属图`:"";if(!confirm(`将自动生成商品文案、匹配官方类目、补全必填属性，并调用生图 API 生成约 ${images} 张图片${skuNote}。会消耗你配置账号的 API 额度，但不会发布商品。继续吗？`))return;try{await api(`/api/drafts/${encodeURIComponent(item.name)}/full-ai-flow`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirmed:true})});await load()}catch(e){alert(e.message)}}
async function showLog(item){$("logRows").textContent="读取中…";$("logDialog").showModal();try{const data=await api(`/api/drafts/${encodeURIComponent(item.name)}/ai-log`);$("logRows").innerHTML="";data.events.forEach(event=>{const row=document.createElement("article");row.className="log-row";const time=document.createElement("small");time.textContent=event.time||"未记录时间";const title=document.createElement("strong");title.textContent=event.event;const pre=document.createElement("pre");pre.textContent=JSON.stringify(event.detail||{},null,2);row.append(time,title,pre);$("logRows").appendChild(row)})}catch(e){$("logRows").textContent=e.message}}
async function batch(action){const names=[...selected];if(action==="recycle"&&!confirm(`将 ${names.length} 个商品移入本机回收站？可从 recycle_bin 恢复。`))return;try{await api("/api/drafts/batch",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,names})});selected.clear();await load()}catch(e){alert(e.message)}}
$("search").oninput=event=>{const q=event.target.value.trim().toLowerCase();filteredItems=processingItems.filter(item=>`${item.title} ${item.source_url} ${item.category_id||""}`.toLowerCase().includes(q));page=1;render()};$("selectAll").onchange=event=>{currentPage().forEach(item=>event.target.checked?selected.add(item.name):selected.delete(item.name));render()};$("enterReviewSelected").onclick=()=>batch("enter_review");$("pauseSelected").onclick=()=>batch("pause");$("copySelected").onclick=()=>batch("copy");$("recycleSelected").onclick=()=>batch("recycle");$("prevPage").onclick=()=>{page--;render()};$("nextPage").onclick=()=>{page++;render()};$("closeLog").onclick=()=>$("logDialog").close();load();
