let opsState=null,opsTab='summary',opsStore='',opsBusy=false;
const opsTabs={summary:'总览',metrics:'经营指标',billing:'账单',orders:'全部订单',messages:'全部消息',pending:'待处理中心',campaigns:'活动',discounts:'批量折扣'};
const opsStates={NOT_QUERIED:'尚未查询',SUCCESS:'已读取',PARTIAL:'部分取得',FAILED:'本次未取得',UNSUPPORTED:'接口不支持',DEPENDENCY_EMPTY:'缺少关联数据',SCHEMA_UNVERIFIED:'账单结构待核对'};
function opsDate(s){return s?new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'尚无快照'}
function opsTable(head,rows){return `<div class="tableWrap"><table><thead><tr>${head.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${head.length}">尚无已取得记录</td></tr>`}</tbody></table></div>`}
function opsCells(a){return '<tr>'+a.map(x=>`<td>${x}</td>`).join('')+'</tr>'}
function opsStatus(s){return `<p><span class="badge">${esc(opsStates[s.state]||s.state)}</span> · 本地快照 ${opsDate(s.time)}</p>${s.error?`<div class="note">${esc(s.error)}</div>`:''}${s.last_attempt?`<div class="note">${esc(s.last_attempt.error)} · ${opsDate(s.last_attempt.time)}，下方仍为旧快照。</div>`:''}${s.note?`<p>${esc(s.note)}</p>`:''}${s.errors?.length?`<div class="note">${s.errors.map(esc).join('<br>')}</div>`:''}`}
function opsQueryButton(kind,label){return `<button data-ops-query="${kind}" ${opsBusy?'disabled':''}>${label}</button>`}
async function showOperations(){opsState=await api('/api/v3/operations');if(opsStore!=='all'&&!opsState.stores.some(s=>s.id===opsStore))opsStore=opsState.active_store_id||opsState.stores[0]?.id||'';if(view==='operations')opsRender()}
function opsRender(){
 if(opsStore==='all'&&!['orders','messages'].includes(opsTab))opsStore=opsState.active_store_id;
 const combine=kind=>{const ss=opsState.stores.map(s=>s.operations[kind]);return {state:ss.every(s=>s.state==='SUCCESS')?'SUCCESS':'PARTIAL',time:ss.map(s=>s.time).filter(Boolean).sort()[0]||null,rows:opsState.stores.flatMap(s=>s.operations[kind].rows.map(r=>({...r,store_id:s.id,store_alias:s.alias}))),total:ss.every(s=>s.total!=null)?ss.reduce((n,s)=>n+s.total,0):null,complete:ss.every(s=>s.state==='SUCCESS'&&s.complete!==false),filters:ss[0]?.filters||{},errors:opsState.stores.filter(s=>s.operations[kind].state!=='SUCCESS').map(s=>s.alias+'：'+(s.operations[kind].error||s.operations[kind].note||opsStates[s.operations[kind].state]))}};
 const row=opsStore==='all'?{id:'all',alias:'全部店铺',operations:{orders:combine('orders'),messages:combine('messages')}}:opsState.stores.find(s=>s.id===opsStore),o=row?.operations||{};
 let body='';
 if(opsTab==='summary'){
  const complete=k=>opsState.stores.every(s=>s.operations[k].state==='SUCCESS'&&s.operations[k].complete!==false);
  const sum=k=>opsState.stores.reduce((n,s)=>n+(s.operations[k].rows?.length||0),0);
  const cards=[['汇总 listing',complete('listings')?sum('listings'):sum('listings')+' 已读（未齐）','按店铺唯一 listing 汇总','discounts','管理指定店铺折扣 →'],['汇总订单',complete('orders')?sum('orders'):sum('orders')+' 已读（未齐）','只汇总已读取的查询范围','orders','查看全部订单 →'],['已保存消息',sum('messages'),'已查询 Pack 会话；不代表全部消息','messages','查看全部消息 →'],['数据健康',opsState.stores.filter(s=>Object.values(s.operations).some(v=>['FAILED','PARTIAL','NOT_QUERIED'].includes(v.state)||v.last_attempt)).length,'未查询、缺权限或刷新失败店铺数','summary',''],['平台结算净额（USD）','待核对','需完整官方账单；不是利润','billing','查看账单明细 →'],['跨境物流费（USD）','待核对','仅能计入官方确认的卖家扣款','billing','核对物流费用 →']];
  body=`<div class="opsHero"><small>MERCADO LIBRE / MULTI-STORE</small><h2>全部店铺运营汇总</h2><p>查看所有登记店铺、目标站点 listing、查询范围内订单和已保存消息。</p><span class="badge">${opsState.stores.length} 个店铺 · 本地快照</span></div><div class="cards opsCards">${cards.map(([t,n,desc,dest,link])=>`<div class="card">${t}<strong>${n}</strong><p>${desc}</p>${link?`<button data-ops-tab="${dest}">${link}</button>`:''}</div>`).join('')}</div>`;
  body+=`<div class="card"><small>GLOBAL SELLING</small><h2>各站点 listing 汇总</h2>${opsTable(['站点','listing 数量','覆盖店铺','状态'],['MLM','MLC','MCO','MLA','MLB'].map(site=>{const hits=opsState.stores.map(s=>new Set(s.operations.listings.rows.flatMap(i=>(i.marketplace_items||[]).filter(m=>m.site_id===site).map(m=>m.item_id))).size);return opsCells([site,complete('listings')?hits.reduce((a,b)=>a+b,0):hits.reduce((a,b)=>a+b,0)+' 已读（未齐）',hits.filter(Boolean).length,complete('listings')?'已读取':'未取得完整映射'])}))}</div><div class="card"><h2>每个店铺的 listing 与订单状态</h2>${opsTable(['店铺','listing 总数','已读订单','数据状态','操作'],opsState.stores.map(s=>opsCells([esc(s.alias),s.operations.listings.total??'未查询',s.operations.orders.total??'未查询',esc(opsStates[s.operations.listings.state]),`<button data-ops-store="${esc(s.id)}">查看店铺</button>`])))}</div><div class="toolbar"><button data-ops-all ${opsBusy?'disabled':''}>刷新全部店铺</button><button data-ops-tab="orders">查看全部订单</button><button data-ops-tab="messages">查看全部消息</button></div><p>刷新全部店铺依次读取 listing 和最近7天订单；账单、会话及其他接口按需查询。站点映射可能重叠，不能将各站点数相加当作唯一 listing 总数。</p>`;
 }else if(!row){body='<div class="note">请先在店铺管理完成授权。</div>'}
 else if(opsTab==='metrics'){
  body=`<div class="card"><h2>经营指标</h2>${opsQueryButton('metrics','查询最新指标')}${opsStatus(o.metrics)}<p>官方 Visits 最近7天；日期范围和站点覆盖以平台响应为准。</p>${opsTable(['站点','访问量','开始','结束'],o.metrics.rows.map(r=>opsCells([esc(r.site_id),r.total_visits??'未返回',esc(r.date_from||'未返回'),esc(r.date_to||'未返回')])))}</div>`;
 }else if(opsTab==='orders'){
  const f=o.orders.filters||{},now=new Date(),begin=new Date(Date.now()-6*86400000),day=d=>d.toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'});
  body=`<div class="card"><h2>近期订单</h2>${opsQueryButton('orders','刷新近期订单')}<div class="toolbar">${[3,7,30,0].map(n=>`<button data-ops-days="${n}">${n?'最近 '+n+' 天':'全部订单'}</button>`).join('')}</div><div class="toolbar"><label>订单状态<select id="opsOrderStatus"><option value="">全部状态</option><option value="paid">已付款</option><option value="confirmed">已确认</option><option value="cancelled">已取消</option></select></label><label>创建日期起<input id="opsFrom" type="date" value="${esc(f.from??day(begin))}"></label><label>创建日期止<input id="opsTo" type="date" value="${esc(f.to??day(now))}"></label>${opsQueryButton('orders','查询订单')}</div>${opsStatus(o.orders)}<p>已读取 ${o.orders.rows.length} 条 / 官方查询总数 ${o.orders.total??'未取得'}。${o.orders.complete===false?'尚未覆盖所有分页。':''}只有成功响应且当前范围为空时才表示0条。</p>${opsTable(['订单 / Pack','商品','创建时间','状态','金额','物流'],o.orders.rows.map(r=>opsCells([(r.store_alias?esc(r.store_alias)+'<br>':'')+esc(r.id)+'<small>'+esc(r.pack_id||'无 Pack')+'</small>',r.items.map(i=>esc(i.title||i.id)+' × '+esc(i.quantity)).join('<br>'),opsDate(r.date_created),esc(r.status),esc(r.total_amount??'未返回')+' '+esc(r.currency_id||''),r.shipment_id?`<button data-ops-shipment="${esc(r.shipment_id)}" data-ops-owner="${esc(r.store_id||opsStore)}">查看物流</button>`:'未返回'])))}</div>`;
 }else if(opsTab==='billing'){
  body=`<div class="card"><h2>销售账单</h2>${opsQueryButton('billing','刷新订单账单')}${opsStatus(o.billing)}<p>先读取订单，再按其站点 Seller ID 分批获取官方账单。平台结算净额和跨境物流费未核对前显示待核对。</p>${opsTable(['订单','Pack','币种','官方金额','净额','物流'],o.billing.rows.map(r=>opsCells(['order_id','pack_id','currency_id','total_amount','net_amount','shipping_cost'].map(k=>esc(r[k]??'未返回')))))}</div>`;
 }else if(opsTab==='messages'){
  body=`<div class="card"><h2>全部店铺买家消息</h2>${opsQueryButton('messages','刷新全部消息')}${opsStatus(o.messages)}<p>按已保存订单的 Pack 读取；不会标为已读，不发送消息。当前显示所选店铺；总览汇总所有店铺。</p>${opsTable(['时间','会话','发送方','内容','状态'],o.messages.rows.map(r=>opsCells([opsDate(r.created),(r.store_alias?esc(r.store_alias)+'<br>':'')+esc(r.pack_id),esc(r.sender),esc(r.text),esc(r.status)])))}</div>`;
 }else if(opsTab==='pending'){
  const p=o.pending;
  body=`<div class="card"><h2>待处理中心</h2>${opsQueryButton('pending','刷新待处理事项')}${opsStatus(p)}<div class="cards"><div class="card">未读买家消息<strong>${p.messages?.state==='SUCCESS'?p.messages.rows.filter(m=>m.sender==='买家'&&!m.read).length:'待查询'}</strong></div><div class="card">开放 Claims<strong>${p.claims?.total??'未取得'}</strong></div><div class="card">未回答问题<strong>${p.questions?.total??'未取得'}</strong></div></div><h3>售后 Claims</h3>${opsTable(['ID','状态','原因','关联记录'],(p.claims?.rows||[]).map(r=>opsCells(['id','status','reason_id','resource_id'].map(k=>esc(r[k])))))}<h3>未回答售前问题</h3>${opsTable(['问题','商品','内容','时间'],(p.questions?.rows||[]).map(r=>opsCells([esc(r.id),esc(r.item_id),esc(r.text),opsDate(r.date_created)])))}</div>`;
 }else if(opsTab==='campaigns'){
  body=`<div class="card"><h2>活动管理</h2>${opsQueryButton('campaigns','刷新')}<button id="opsCampaignDraft">创建活动</button>${opsStatus(o.campaigns)}${row.auth_type==='CBT'?'<div class="note">当前为 CBT 授权；本模块不提交国家站点促销，请到目标国家卖家中心管理。</div>':''}${opsTable(['活动','类型','状态','开始','结束'],o.campaigns.rows.map(r=>opsCells(['name','type','status','start_date','finish_date'].map(k=>esc(r[k])))))}<div id="opsCampaignPanel"></div></div>`;
 }else if(opsTab==='discounts'){
  body=`<div class="card"><h2>批量折扣</h2>${opsQueryButton('listings','刷新')}<div class="toolbar"><label>搜索商品<input id="opsItemSearch" placeholder="商品 ID 或标题"></label><label>折扣 (%)<input id="opsDiscount" type="number" min="0.01" max="99.99" step="0.01" value="10"></label><button id="opsDiscountPreview">生成折扣预览</button></div>${opsStatus(o.listings)}${opsTable(['选择','商品','价格','状态'],o.listings.rows.map(r=>`<tr data-ops-item="${esc((r.id+' '+r.title).toLowerCase())}"><td><input type="checkbox" data-ops-id="${esc(r.id)}" aria-label="选择 ${esc(r.title)}"></td><td>${esc(r.title)}<small>${esc(r.id)}</small></td><td>${esc(r.price)} ${esc(r.currency_id)}</td><td>${esc(r.status)}</td></tr>`))}<div id="opsDiscountResult"></div></div>`;
 }
 mount(`<h1>店铺运营</h1><p>围绕商品、活动、订单和买家沟通安排日常工作。打开页面只读本地快照，点击查询或刷新才访问平台。</p><div class="opsTabs">${Object.entries(opsTabs).map(([k,t])=>`<button data-ops-tab="${k}" class="${k===opsTab?'primary':''}">${t}</button>`).join('')}</div>${opsTab!=='summary'?`<label class="opsStoreLabel">${['campaigns','discounts'].includes(opsTab)?'目标店铺':'查看店铺'}<select id="opsStoreSelect">${['orders','messages'].includes(opsTab)?`<option value="all" ${opsStore==='all'?'selected':''}>全部店铺</option>`:''}${opsState.stores.map(s=>`<option value="${esc(s.id)}" ${s.id===opsStore?'selected':''}>${esc(s.alias)} (${esc(s.auth_type)})</option>`).join('')}</select></label>`:''}${body}`);
 if($('opsStoreSelect'))$('opsStoreSelect').onchange=()=>{opsStore=$('opsStoreSelect').value;opsRender()};
 if($('opsOrderStatus'))$('opsOrderStatus').value=o.orders.filters?.status||'';
 if($('opsItemSearch'))$('opsItemSearch').oninput=()=>{const q=$('opsItemSearch').value.toLowerCase();document.querySelectorAll('[data-ops-item]').forEach(r=>r.hidden=!r.dataset.opsItem.includes(q))};
 if($('opsDiscountPreview'))$('opsDiscountPreview').onclick=async()=>{try{const d=await api('/api/v3/operations/discount-preview',{store_id:opsStore,discount:$('opsDiscount').value,item_ids:[...document.querySelectorAll('[data-ops-id]:checked')].map(i=>i.dataset.opsId)});$('opsDiscountResult').innerHTML=`<h3>折扣预览 · ${esc(row.alias)}</h3><div class="note">${esc(d.note)} · 本次未提交</div>${opsTable(['商品','原价','预览折后价','币种'],d.rows.map(r=>opsCells([esc(r.title),esc(r.original),esc(r.discounted),esc(r.currency)])))}`}catch(e){notify(e.message,true)}};
 if($('opsCampaignDraft'))$('opsCampaignDraft').onclick=()=>{$('opsCampaignPanel').innerHTML='<h3>创建活动预览</h3><label>活动名称<input id="opsCampaignName"></label><p>需要目标国家站点授权、官方活动资格和起止日期。本版仅保留创建入口，外部提交尚未实现，不能当作已创建。</p>'};
}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||view!=='operations')return;
 if(b.dataset.opsShipment){try{const d=await api('/api/v3/operations/shipment',{store_id:b.dataset.opsOwner||opsStore,shipment_id:b.dataset.opsShipment});$('logContent').innerHTML='<h3>官方物流详情</h3><pre>'+esc(JSON.stringify(d.shipment,null,2))+'</pre>';$('log').showModal()}catch(e){notify(e.message,true)}return}if(b.dataset.opsTab){opsTab=b.dataset.opsTab;opsRender();return}if(b.dataset.opsStore){opsStore=b.dataset.opsStore;opsTab='metrics';opsRender();return}
 if(b.dataset.opsDays!==undefined){const n=Number(b.dataset.opsDays),d=new Date(Date.now()-(n-1)*86400000);$('opsFrom').value=n?d.toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'}):'';$('opsTo').value=n?new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'}):'';return}
 if(!b.dataset.opsQuery&&!b.hasAttribute('data-ops-all'))return;if(opsBusy)return;opsBusy=true;b.disabled=true;notify('正在查询官方只读数据…');
 try{let options={};if(b.dataset.opsQuery==='orders')options={from:$('opsFrom').value,to:$('opsTo').value,status:$('opsOrderStatus').value};if(b.hasAttribute('data-ops-all')){for(const s of opsState.stores){await api('/api/v3/operations/query',{store_id:s.id,kind:'listings'});await api('/api/v3/operations/query',{store_id:s.id,kind:'orders',options:{from:new Date(Date.now()-6*86400000).toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'}),to:new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'})}})}}else if(opsStore==='all'){for(const s of opsState.stores)await api('/api/v3/operations/query',{store_id:s.id,kind:b.dataset.opsQuery,options})}else await api('/api/v3/operations/query',{store_id:opsStore,kind:b.dataset.opsQuery,options});notify('查询结束，结果及失败项见下方快照');await showOperations()}catch(e){notify(e.message,true)}finally{opsBusy=false;if(view==='operations')opsRender()}
});
