const app=document.querySelector("#app"),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const dimensions=r=>(r.dimensions_cm||[]).every(v=>v!=null)?r.dimensions_cm.join(" × ")+" cm":"未取得";
const steps='<section class="steps"><div><b>1</b>商品处理</div><div><b>2</b>商品审核</div><div class="active"><b>3</b>发布中心</div></section>';
let rows=[],filter="pending",query="",selected=new Set();
async function api(url,options){const r=await fetch(url,options),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"请求失败");return d}
const post=(url,body={})=>api(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
const statusOf=r=>r.publish_status||"pending",siteNames=r=>(r.sites_to_sell||[]).map(x=>typeof x==="string"?x:x.site_id).join("、")||"未选择";
const label=s=>({pending:"待发布",pending_confirmation:"待确认",success:"全部成功",partial:"部分成功",failed:"失败"}[s]||s);
const canSelect=r=>statusOf(r)==="pending"&&r.publish_ready;
function skuResults(r){return (r.publish_variants||[]).length?'<div class="site-results">'+r.publish_variants.map(v=>'<div><strong>'+esc(v.seller_sku||"SKU")+'</strong>'+(v.sites||[]).map(s=>'<span class="site-'+esc(s.status)+'">'+esc(s.site_id)+" "+esc(label(s.status))+(s.item_id?" · "+esc(s.item_id):"")+"</span>").join("")+"</div>").join("")+"</div>":""}
function render(){
 const shown=rows.filter(r=>statusOf(r)===filter&&(!query||(`${r.listing_title||""} ${r.title||""} ${r.name||""} ${r.category_id||""}`).toLowerCase().includes(query)));
 const counts={pending:0,pending_confirmation:0,success:0,partial:0,failed:0};rows.forEach(r=>counts[statusOf(r)]=(counts[statusOf(r)]||0)+1);
 const selectable=shown.filter(canSelect),checked=selectable.filter(r=>selected.has(r.name));
 app.innerHTML=`<header><div><div class="crumb">工作台 / 发布中心</div><h1>发布中心</h1><p>先预览每个 SKU 与站点请求；真实发布仍需当次确认。</p></div></header>${steps}
 <section class="panel top"><div class="tabs">${["pending","pending_confirmation","success","partial","failed"].map(s=>`<button data-tab="${s}" class="${filter===s?"active":""}">${label(s)} ${counts[s]}</button>`).join("")}</div><select><option>Mercado Libre Store（CBT）</option></select></section>
 <section class="target"><label><input type="checkbox" checked disabled> Mercado Libre Store（CBT）</label><small>CBT：MLB 仅 Remote；MLM 可按账号能力使用 Remote 或 Full</small></section>
 <section class="panel"><div class="toolbar"><h2>${label(filter)}商品</h2><div><input id="search" value="${esc(query)}" placeholder="搜索标题、SKU、类目或错误"><button id="searchButton">搜索</button><span>${shown.length} 条结果</span></div></div>
 <div class="batch"><label><input id="selectAll" type="checkbox" ${selectable.length&&checked.length===selectable.length?"checked":""} ${selectable.length?"":"disabled"}> 全选当前页</label><b>已选 ${selected.size} 条</b><span>逐条保存结果，单条失败不影响其他商品</span><button id="batchPublish" ${selected.size?"":"disabled"}>批量发布</button></div>
 <div>${shown.length?shown.map(r=>{const s=statusOf(r),issue=["failed","partial"].includes(s)?`${label(s)}：${r.publish_error||"请查看站点结果"}`:r.publish_ready?"发布字段已齐":`待补：${(r.publish_issues||["发布字段"]).join("、")}`;const primary=s==="partial"?`<button data-retry="${esc(r.name)}">只重试失败站点</button>`:s==="failed"?`<button data-publish="${esc(r.name)}" ${r.publish_ready?"":"disabled"}>编辑后重新发布</button>`:s==="pending"?`<button data-publish="${esc(r.name)}" ${r.publish_ready?"":"disabled"}>发布（需确认）</button>`:"";const refresh=["pending_confirmation","partial","success"].includes(s)?`<button class="secondary" data-refresh="${esc(r.name)}">回查结果</button>`:"";return `<article class="publish-row"><input type="checkbox" data-select="${esc(r.name)}" ${selected.has(r.name)?"checked":""} ${canSelect(r)?"":"disabled"}><img src="${esc(r.thumbnail?`/api/image-proxy?url=${encodeURIComponent(r.thumbnail)}`:"")}" alt=""><div class="product"><b>${esc(r.listing_title||r.title)}</b><small>草稿：${esc(r.name.replace("-draft.json",""))} · ${esc(r.sku_count||1)} SKU</small><dl><div><dt>站点</dt><dd>${esc(siteNames(r))}</dd></div><div><dt>类目</dt><dd>${esc(r.category_id||"未指定")}</dd></div><div><dt>计价</dt><dd>各 SKU / 站点独立</dd></div><div><dt>库存</dt><dd>${esc(r.available_quantity??"各 SKU 独立")}</dd></div><div><dt>重量</dt><dd>${esc(r.weight_g??"-")} g</dd></div><div><dt>尺寸</dt><dd>${esc(dimensions(r))}</dd></div><div class="qualification"><dt>发布资格</dt><dd><span class="badge">${esc(issue)}</span></dd></div></dl>${skuResults(r)}</div><div class="actions"><a href="/editor?draft=${encodeURIComponent(r.name)}">编辑</a><button class="secondary" data-preview="${esc(r.name)}">校验与预览</button>${refresh}${primary}<button class="secondary" data-copy="${esc(r.name)}">复制为新商品</button></div></article>`}).join(""):'<div class="empty">当前分栏没有记录</div>'}</div></section>
 <dialog id="previewDialog"><button class="dialog-close" data-close>关闭</button><h2>SKU 发布校验与请求预览</h2><div id="previewBody"></div></dialog>`;
}
async function load(){const d=await api("/api/drafts");rows=(d.items||[]).filter(r=>r.approved);selected=new Set([...selected].filter(n=>rows.some(r=>r.name===n&&canSelect(r))));render()}
async function preview(name){const p=(await api(`/api/drafts/${encodeURIComponent(name)}/publish-preview`)).preview,c=p.category_validation||{},dialog=document.querySelector("#previewDialog");const mappings=(c.sites||[]).map(x=>`<tr><td>${esc(x.site_id)}</td><td>${esc(x.category_id)}</td><td>${esc(x.category_name||"未取得")}</td><td>${x.compatible?"通过":"不兼容"}</td></tr>`).join("");document.querySelector("#previewBody").innerHTML=`<p class="${p.valid?"preview-ok":"warning"}">${p.valid?"全部 SKU 与站点类目校验通过":"存在阻塞项，不能发布"}</p><h3>站点类目映射</h3><p>CBT：${esc(c.category_id||"-")} · ${esc(c.category_name||"未取得")} · ${esc(c.domain||"未取得商品域")}</p>${c.issues?.length?`<p class="warning">${esc(c.issues.join("；"))}</p>`:""}<table><thead><tr><th>站点</th><th>映射类目</th><th>名称</th><th>结果</th></tr></thead><tbody>${mappings||'<tr><td colspan="4">未取得</td></tr>'}</tbody></table><h3>SKU 校验</h3><table><thead><tr><th>SKU</th><th>站点</th><th>图片</th><th>结果</th></tr></thead><tbody>${p.sku_validation.map(x=>`<tr><td>${esc(x.seller_sku||x.sku_id)}</td><td>${x.site_count}</td><td>${x.image_count}</td><td>${x.valid?"通过":esc(x.issues.join("；"))}</td></tr>`).join("")}</tbody></table><p>${esc(p.note)}</p><pre>${esc(JSON.stringify(p.request,null,2))}</pre>`;dialog.showModal()}
async function publishOne(row,retry){if(!confirm(`${retry?"只重试失败站点":"发布全部 SKU"}：${row.listing_title||row.title}\n站点：${siteNames(row)}\n这会真实提交到 Mercado Libre，确认继续？`))return;await post(`/api/drafts/${encodeURIComponent(row.name)}/${retry?"publish-retry":"publish"}`,{confirmed:true});await load()}
document.addEventListener("click",async e=>{try{const tab=e.target.closest("[data-tab]");if(tab){filter=tab.dataset.tab;render();return}if(e.target.id==="searchButton"){query=(document.querySelector("#search")?.value||"").trim().toLowerCase();render();return}if(e.target.matches("[data-close]")){document.querySelector("#previewDialog")?.close();return}const p=e.target.closest("[data-preview]");if(p){await preview(p.dataset.preview);return}const b=e.target.closest("[data-publish]");if(b){await publishOne(rows.find(r=>r.name===b.dataset.publish),false);return}const t=e.target.closest("[data-retry]");if(t){await publishOne(rows.find(r=>r.name===t.dataset.retry),true);return}const f=e.target.closest("[data-refresh]");if(f){await post(`/api/drafts/${encodeURIComponent(f.dataset.refresh)}/publish-refresh`);await load();return}const c=e.target.closest("[data-copy]");if(c){const d=await post("/api/drafts/batch",{action:"copy",names:[c.dataset.copy]});alert(`已复制为新商品：${d.results?.[0]?.copy||"完成"}`);await load();return}if(e.target.id==="batchPublish"){const names=[...selected];if(names.length&&confirm(`将真实批量发布 ${names.length} 个商品，确认继续？`)){const d=await post("/api/publish/batch",{confirmed:true,names}),failed=(d.results||[]).filter(x=>!x.ok);alert(failed.length?`批量完成，${failed.length} 个失败。`:`批量发布已提交：${names.length} 个。`);selected.clear();await load()}}}catch(error){alert(`操作失败：${error.message}`);await load()}});
document.addEventListener("change",e=>{if(e.target.matches("[data-select]")){e.target.checked?selected.add(e.target.dataset.select):selected.delete(e.target.dataset.select);render()}if(e.target.id==="selectAll"){rows.filter(r=>statusOf(r)===filter&&canSelect(r)).forEach(r=>e.target.checked?selected.add(r.name):selected.delete(r.name));render()}});
load().catch(error=>app.innerHTML=`<div class="warning">${esc(error.message)}</div>`);
